In [45]:
import numpy as np

In [46]:
a1 = np.array([1,2,3])

In [47]:
a1

array([1, 2, 3])

In [48]:
a1.ndim

1

In [49]:
type(a1)

numpy.ndarray

In [50]:
a1.size

3

In [51]:
a2 = np.array([[1,2,3],[4,5,6]])

In [52]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1.shape

(3,)

In [56]:
a2.shape

(2, 3)

In [57]:
a3.shape

(2, 3, 3)

In [58]:
import pandas as pd

In [59]:
df=pd.DataFrame(a2)

In [60]:
df

0  1  2
0  1  2  3
1  4  5  6

# Creating Arrays

In [61]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [62]:
sample_array.dtype

dtype('int64')

In [63]:
ones = np.ones( (2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
 zeros = np.zeros((10,10))

In [65]:
zeros
type(ones)

numpy.ndarray

In [66]:
zeros.dtype

dtype('float64')

In [67]:
random_array=np.random.rand(10,10)

In [68]:
random_array

array([[0.39200156, 0.93959276, 0.21291858, 0.81329627, 0.40364858,
        0.58672092, 0.18599889, 0.81232251, 0.58084741, 0.44693254],
       [0.79808141, 0.54427185, 0.41841659, 0.01915666, 0.68377373,
        0.48809792, 0.22057967, 0.55054305, 0.52259111, 0.48755248],
       [0.26303148, 0.52728579, 0.98446573, 0.62342345, 0.62955693,
        0.9099729 , 0.96251949, 0.5850998 , 0.16489774, 0.39159332],
       [0.94455493, 0.34339118, 0.70507037, 0.4628868 , 0.38679069,
        0.52843256, 0.82168992, 0.63847702, 0.86288872, 0.63662654],
       [0.99929706, 0.51778008, 0.32761664, 0.09877324, 0.5667664 ,
        0.21520794, 0.01179079, 0.29921532, 0.03897743, 0.97621382],
       [0.55145308, 0.07171621, 0.34006782, 0.24290239, 0.10735082,
        0.77033058, 0.35060155, 0.18764274, 0.91265269, 0.86114826],
       [0.39889823, 0.54633644, 0.45037544, 0.69359919, 0.21384609,
        0.3237989 , 0.73989292, 0.18257051, 0.69602194, 0.52673506],
       [0.19849106, 0.65046402, 0.5097764

In [69]:
random_array.dtype

dtype('float64')

In [70]:
type(random_array)

numpy.ndarray

In [71]:
np.random.seed(7)
random_array_seed = np.random.randint(10, size=(5,3))

In [72]:
random_array_seed

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

In [73]:
np.unique(random_array_seed)

array([3, 4, 6, 7, 8, 9])

In [74]:
a1[0]

1

In [75]:
a2[0][0]

1

In [76]:
a3[:1, :1, :3]

array([[[1, 2, 3]]])

In [77]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [78]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [79]:
a1+ones

array([2., 3., 4.])

In [83]:
%timeit sum(a3)
%timeit np.sum(a3)

4 µs ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.29 µs ± 56.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [84]:
massive_array = np.random.random(10000)
massive_array[:10]

array([0.39200156, 0.93959276, 0.21291858, 0.81329627, 0.40364858,
       0.58672092, 0.18599889, 0.81232251, 0.58084741, 0.44693254])

In [88]:
%timeit np.mean(massive_array)
np.mean(massive_array)

21.3 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


0.5037099659172491

In [89]:
%timeit np.std(massive_array)
np.std(massive_array)

59.5 µs ± 370 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


0.2868506192832226

In [90]:
%timeit np.var(massive_array)
np.var(massive_array)

47 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


0.0822832777831683

In [91]:
%timeit np.sqrt(np.var(massive_array))
np.sqrt(np.var(massive_array))

50.7 µs ± 459 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


0.2868506192832226

In [92]:
a2_reshape = a2.reshape(2,3,1)

In [93]:
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [94]:
a2_reshape*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [98]:
np.random.seed(0)

mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(3,3))

In [101]:
dotprod = np.dot(mat1, mat2)
dotprod

array([[ 57,  59,  62],
       [155, 100, 137],
       [ 76,  42,  64],
       [134,  83, 117],
       [121,  72, 105]])

In [103]:
np.random.seed(0)
sales_amounts = np.random.randint(100, size=(5,3))
sales_amounts

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [104]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               44             47             64
Tues              67             67              9
Wed               83             21             36
Thurs             87             70             88
Fri               88             12             58

In [106]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [108]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])

In [109]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [110]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([1584, 1314, 1430, 2486, 1672])